[2024-06-18T14:22:33.253+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T14:22:33.266+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:37:27.350691+00:00 [queued]>
[2024-06-18T14:22:33.269+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:37:27.350691+00:00 [queued]>
[2024-06-18T14:22:33.270+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T14:22:33.281+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 08:37:27.350691+00:00
[2024-06-18T14:22:33.282+0545] {standard_task_runner.py:63} INFO - Started process 6597 to run task
[2024-06-18T14:22:33.284+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-18T08:37:27.350691+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp6muubx1z']
[2024-06-18T14:22:33.284+0545] {standard_task_runner.py:91} INFO - Job 13: Subtask send_mail
[2024-06-18T14:22:33.309+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-18T08:37:27.350691+00:00 [running]> on host Heathen.
[2024-06-18T14:22:33.358+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='avyu' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T08:37:27.350691+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T08:37:27.350691+00:00'
[2024-06-18T14:22:33.359+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T14:22:33.366+0545] {logging_mixin.py:188} WARNING - /root/apache_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T14:22:33.367+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T14:22:35.324+0545] {email.py:282} INFO - Sent an alert email to ['avyuthan364@gmail.com']
[2024-06-18T14:22:37.189+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T14:22:37.192+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-18T08:37:27.350691+00:00, execution_date=20240618T083727, start_date=20240618T083733, end_date=20240618T083737
[2024-06-18T14:22:37.205+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T14:22:37.213+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T14:22:37.214+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
